---
title: "Iteration and List Columns"
author: Yuen
date: 11/18/2021
output: 
  github_document
---

## define the theme for all the ggplots!

```{r setup}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color.discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Lists 

You can put anything in a list

```{r}
l = list(
  vec_numeric = 5:8,
  vec_logical = c(T,T,F,T,F,F),
  mat = matrix(1:8, nrow = 2, ncol = 4),
  summary = summary(rnorm(100))
)

```

```{r}
l$vec_numeric
l[[1]]
l[["vec_numeric"]]
mean(l[["vec_numeric"]])
l[["vec_numeric"]][1:3]

```

## for loop

create a new list

```{r}
list_norm = 
  list(
    a = rnorm(20, mean = 3, sd = 1),
    b = rnorm(30, mean = 0, sd = 5),
    c = rnorm(40, mean = 10, sd = 0.2),
    d = rnorm(20, mean = -3, sd = 1)
  )

```

```{r}
list_norm
```

Pause and get my old function

```{r}
mean_and_sd = function(x) {
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  if (length(x) <3) {
    stop("Input must have at least 3 numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean= mean_x,
    sd = sd_x
  )
}

```

I can apply that function to each list element

```{r}
mean_and_sd(list_norm[[1]])
mean_and_sd(list_norm[[2]])
mean_and_sd(list_norm[[3]])
mean_and_sd(list_norm[[4]])
```

Let's use a for loop:

```{r}
output = vector("list",length = 4)
#output[[1]] = mean_and_sd(list_norm[1])

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norm[[i]])
}
```

## Let's try map!

```{r}
output = map(list_norm,mean_and_sd)
```

what if you want a different function?

```{r}
output = map(list_norm, median)
output = map(list_norm, IQR)
```


```{r}
#double
output = map_dbl(list_norm, median)
```

```{r}
output = map_df(list_norm, mean_and_sd, .id = "input")
```

## List columns

```{r}
listcol_df =
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norm
  )
```

```{r}
listcol_df %>% pull(name)
listcol_df %>% pull(samp)

listcol_df %>% 
  filter(name == "a")

```

Let's try some operations

```{r}
listcol_df$samp
listcol_df$samp[[1]]
mean_and_sd(listcol_df$samp[[2]])

```

can I just ... map?
```{r}
map(listcol_df$samp, mean_and_sd)
```


So can I add a list column to the existing df?

```{r}
listcol_df = 
  listcol_df %>% 
    mutate(summary = map(samp,mean_and_sd),
           medians = map_dbl(samp, median))



```











