---
title: "Iteration"
author: Yuen
date: 11/18/2021
output: 
  github_document
---

## define the theme for all the ggplots!

```{r setup}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color.discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Do something simple

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec))/sd(x_vec)

```

I want a function to compute z scores

```{r}
z_scores = function(x){
  
  if (!is.numeric(x)){
    stop("Input must be numeric")
  }
  
  if (length(x)<3){
    stop("Input must have at least 3 numbers")
  }
  
  
  z = (x - mean(x)) / sd(x)
  return(z)
}

z_scores(x_vec)



```

Try my function on some other things. These should give errors

```{r, error = T}
z_scores(3)
z_scores("my name is Jeff")
z_scores(mtcars)
z_scores(c(T,T,F,T))
```


## Multiple outputs

```{r}
mean_and_sd = function(x){
  
  if (!is.numeric(x)){
    stop("Input must be numeric")
  }
  
  if (length(x)<3){
    stop("Input must have at least 3 numbers")
  }
  
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}





```

Check that the function works.

```{r}
x_vec = rnorm(1000, mean =3, sd = 4)
mean_and_sd(x_vec)
```

## Multiple inputs

I'd like to do this with a function
```{r}
sim_data = 
  tibble(
    x = rnorm(n = 100, mean = 4, sd = 3)
  )

sim_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )

```


```{r}
#true mean - mu, true sd - sigma
#and set up the default values if not defined
sim_mean_sd = function(samp_size, mu = 3, sigma = 4){
  sim_data = 
    tibble(
      x = rnorm(n = samp_size, mean = mu, sd = sigma)
    )
  
  sim_data %>% 
    summarize(
      mean = mean(x),
      sd = sd(x)
    )
}

sim_mean_sd(samp_size = 100, mu = 6, sigma = 3)

```






